

baseurl: "" 
url: "https://luninglin.github.io" 

title: Luning Lin | Homepage
author: Luning Lin
email: luninglin@zju.edu.cn
description: >
  Personal homepage of Luning Lin, a Ph.D. student at the College of Information and Electronic Engineering, Zhejiang University.
  My research focuses on Array Signal Processing, Integrated Sensing and Communication (ISAC), and Wireless Communication.

# -----------------
# 主题和插件设置
# -----------------
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# -----------------
# Plainwhite 主题的专属设置
# -----------------
plainwhite:
  name: Luning Lin (林鹿宁)
  tagline: Ph.D. Student in Electronic Science Technology
  date_format: "%b %-d, %Y"

  sitemap: true
  search: true
  dark_mode: true
  
  portfolio_image: "assets/profile.jpg" 

  social_links:
    google_scholar: "https://scholar.google.com/citations?user=POUuJlIAAAAJ&hl=zh-CN"
    email: luninglin@zju.edu.cn

  navigation:
    - title: Home
      url: "/"
    - title: Publications
      url: "/publications"
    - title: Projects
      url: "/projects"

